version: '3'

services:
  challenge-backend-pg-database:
    container_name: challenge-backend-pg-database
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_ENGLISH_DB}
      POSTGRES_USER: ${POSTGRES_ENGLISH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ENGLISH_PASSWORD}

    volumes:
      - ./data:/var/lib/postgresql/data

    ports:
      - ${POSTGRES_PORT}:5432

    networks:
      - challenge-backend-network

networks:
  challenge-backend-network:
    driver: bridge
